### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by jyothiswbpro** [bengreenier/node-dss#6]
> node bin/dss.js

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES: permission denied 0.0.0.0:3000
    at Server.setupListenHandle [as _listen2] (net.js:1262:19)
    at listenInCluster (net.js:1327:12)
    at Server.listen (net.js:1414:7)
    at Object.<anonymous> (I:\node-dss\bin\dss.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
Emitted 'error' event at:
    at emitErrorNT (net.js:1306:8)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dss@1.0.0 start: `node bin/dss.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dss@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by bengreenier** [comment]
Poer `3000` is already in use on your machine. Please run `set PORT=3001` (replacing `3001` with any unused port on your machine) and start again.
